### PR TITLE
Clean css and change selectors

### PR DESCRIPTION
**Pull request by Gaserd**

### CODE REVIEW

**Comment by andywer** [comment]
Hey @Gaserd!
Thanks for your PR. I already saw it, but won't be able to look it through until this afternoon (earliest). Sorry and thanks for your help! I am just terribly busy this week :-/

**Comment by Gaserd** [comment]
@andywer No problem! I'm patient 👍

**Comment by andywer** [comment]
Had a look at it and fixed two very minor (code) issues.

One more suggestion: How about changing the plugin documentation link's background color to a darker grey on :hover instead of underlining the question mark?

**Comment by Gaserd** [comment]
@andywer nice idea
:DONE

**Comment by Gaserd** [comment]
@andywer  ?

**Comment by andywer** [comment]
Hey @Gaserd. Sorry, I have been traveling the whole day yesterday. I tested it and merged the changes into the `develop` branch ;)

**Comment by andywer** [comment]
One more suggestion: Do you like the idea to make the triangle-right icon completely white (non-transparent)?

See screenshot:
bildschirmfoto 2016-08-18 um 10 39 01

**Comment by Gaserd** [comment]
@andywer hmmm... yeah, this is look better

**Comment by andywer** [comment]
Ok. Everything is in https://github.com/andywer/postcss-debug/tree/develop now.

Any objections from your side or ready to publish? ;)

**Comment by Gaserd** [comment]
@andywer I ready to publish! 👍

**Pull request merged**
