### PR TITLE
[ui] change block and add column

### PR DESCRIPTION
**Pull request by Gaserd**
- add input of search
- add 2 column
- small fixes

### CODE REVIEW

**Comment by andywer** [comment]
I need to do:
- [x] Make file filter input work
- [x] Configurable sample data (now the `build/app.js` and `dev/sample-data.js` files are unnecessary big)

Right?

**Comment by Gaserd** [comment]
@andywer Yeap :)

**Comment by andywer** [comment]
Just pushed to https://github.com/andywer/postcss-debug/tree/develop. Includes your new UI, working search field, cleaner sample data code, fixed positioning and useful help links.

If you don't have further objections or almost-ready improvements I would release the current state as 0.3.0 in the next hours.

Thanks a lot so far. It looks really cool now :)

**Comment by Gaserd** [comment]
@andywer Ok. We made your project so better :) Maybe close this Pull Request ?

**Comment by andywer** [comment]
@Gaserd @ai Any more changes you would like to see in 0.3.0?

**Comment by ai** [comment]
Remove common parts for file paths :). (at least screenshot still contain it)

**Comment by ai** [comment]
Also please write tweet about 0.3 with screenshot, I will retweet it by PostCSS account

**Comment by andywer** [comment]
Ahhh, right. Done!

Of course I tweet that it just got a new UI ;)
https://twitter.com/andywritescode/status/738074161076183040

**Comment by ai** [comment]
Can I ask you post it again with screenshot?

**Comment by andywer** [comment]
👍

**Comment by Gaserd** [comment]
@andywer No. I want to make a few changes even after the 0.3.0 and I'm so happy with everything :)

**Pull request merged**
