### PR TITLE
updated UI

### PR DESCRIPTION
**Pull request by Gaserd**
- add new UI
- add icon
- more add :)

### CODE REVIEW

**Comment by andywer** [comment]
Cool! 👍👍

I will test it later when I have got some time. Thanks for your work!

**Comment by Gaserd** [comment]
@andywer Okey, i will wait your test 👍

**Comment by Gaserd** [comment]
@andywer I set small fix and add event for change theme, and we have dark theme too 👍 
Change theme : shift + d

**Comment by andywer** [comment]
Ok, but dark theme should be the default. Got 62% in the poll :)

Btw: We could add a simple theme switch to the footer.

**Comment by Gaserd** [comment]
- added tip for change theme

I think we need start red theme UI, because Russian Community choosed Dark theme 40% :( 
And We need real testing for our UI for choose UI

**Comment by andywer** [comment]
:-/

We should have done only one poll 😅. Yeah, but red as default and a switch is fine, too.

**Comment by Gaserd** [comment]
@andywer Good 👍  Thanks!

**Comment by andywer** [comment]
Looks pretty cool! But I've got some minor questions:
1. Do we need both the "documentation" and "github" link?
2. Wouldn't a small text link be more convenient to switch the theme? (Like "Switch to dark theme" which turns into "Switch to red theme" after switching)

Suggestion: How about saving the chosen theme in the browser's local storage? It will then remember your favorite theme when you re-open the debugger later.

**Comment by Gaserd** [comment]
Yeap, we need use localStorage 👍 
1. Yes, because github link leads code and documentation link leads wiki for our plugin, documentation link need for the future, you can hide it.
2. No, we talk our users and we provide them small hint

**Comment by andywer** [comment]
Quick update: I am short of time today, but I managed to clean up the keyboard listener code, integrate it into the app bundle and save the selected theme to the browser's local storage.

Your PR has already bin merged into the develop branch, but my newest changes are not yet pushed.

**Comment by Gaserd** [comment]
@andywer Okay, it is right!

**Comment by Gaserd** [comment]
- added new logo

**Comment by Gaserd** [comment]
- added mobile version UI

**Comment by andywer** [comment]
@Gaserd Say... Where did the links to the plugin documentations go?

**Comment by andywer** [comment]
@Gaserd Ahhh... I found it. But it's not dynamic and not clickable anymore... 🙈

**Comment by andywer** [comment]
On my local develop branch I merged the changes and made static stuff work, but it will take some time to clean up the CSS sheets. They keep growing wild.

I guess I will shift to a webpack / css modules setup to get rather maintainable stylesheets.

One more thing I noticed: I made the plugin help link dynamic again, but it's very likely that you accidentally open the plugin help when you just want to open the snapshot contents or vice versa. Maybe we can find a solution for this :)

**Comment by Gaserd** [comment]
@andywer  hey, you don't worry about the documentation
and i dоnt have nothing against webpack
and i can wait so more

**Pull request closed without merging**
