### PR TITLE
new UI

### PR DESCRIPTION
**Pull request by Gaserd**
Change UI :
- add main color
- fix font-family
- fix tabs
- change font-size (22px -> 15px)
- remove Bootstrap
  and small fixes

### CODE REVIEW

**Comment by andywer** [comment]
Cool, thank you!

Already merged it into develop branch. But we should probably set the header's left padding/margin to same as the main content's, right?

**Comment by Gaserd** [comment]
@andywer Yes 👍  And i soon add new features for UI

**Comment by andywer** [comment]
Awesome! I merged, but did not yet re-release.

**Comment by andywer** [comment]
PS: Pull once from this repo to get two minor fixes. Just changed the footer link styling slightly (text-decoration) & matched the header margin/padding.

**Comment by Gaserd** [comment]
@andywer Thx 👍

**Pull request merged**
